import 'package:get/get.dart';
import 'package:medtrack/core/utils/string_manger.dart';
import 'package:medtrack/routes/routes_constants.dart';

class AppLocal extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'loginWelcomeSentence': AppStrings.loginWelcomeSentence,
          'login': AppStrings.login,
          'userEmailHint': AppStrings.userEmailHint,
          'userNameHint': AppStrings.userNameHint,
          'userPassWordHint': AppStrings.userPassWordHint,
          'loginWithGoogle': AppStrings.loginWithGoogle,
          'notHavingAccount': AppStrings.notHavingAccount,
          'register': AppStrings.register,
          'signUp': AppStrings.signUp,
          'signUpWithGoogle': AppStrings.signUpWithGoogle,
          'alreadyHaveAccount': AppStrings.alreadyHaveAccount,
          'signIn': AppStrings.signIn,
          'signUpWelcomeSentence': AppStrings.signUpWelcomeSentence,
          'facebookSentence': AppStrings.facebookSentence,
          'googleSentence': AppStrings.googleSentence,
          'Doctor meeting': AppStrings.doctorDiagnosis,
          'Medical History': AppStrings.medicalHistory,
          'Body Vitals': AppStrings.bodyVitals,
          'Medical Images': AppStrings.medicalImages,
          'hi': AppStrings.hi,
          'Home': AppStrings.home,
          'Prescriptions': AppStrings.prescriptions,
          'Analytics': AppStrings.analytics,
          'Profile': AppStrings.profile,
          'Good Morning': AppStrings.goodMorning,
          'Good Evening': AppStrings.goodEvening,
          'Date': AppStrings.date,
          'Doctor Name': AppStrings.doctorName,
          'complain': AppStrings.complain,
          'Doctor Diagnosis': AppStrings.diagnosis,
          'pulse': AppStrings.pulse,
          'pressure': AppStrings.pressure,
          'sys': AppStrings.sys,
          'dia': AppStrings.dia,
          'mmhg':AppStrings.pressureUnit,
          'weight':AppStrings.weight,
          'kg':AppStrings.weightUnit,
          'Measurement date':AppStrings.measurementDate,
          'Add the new measurements':AppStrings.addMeasurement,
          'welcome input ':AppStrings.welcomeInputDia,
        },
        'ar': {
          'loginWelcomeSentence': AppStrings.loginWelcomeSentenceAr,
          'login': AppStrings.loginAr,
          'userEmailHint': AppStrings.userEmailHintAr,
          'userNameHint': AppStrings.userNameHintAr,
          'userPassWordHint': AppStrings.userPassWordHintAr,
          'loginWithGoogle': AppStrings.loginWithGoogleAr,
          'notHavingAccount': AppStrings.notHavingAccountAr,
          'register': AppStrings.registerAr,
          'signUp': AppStrings.signUpAr,
          'signUpWithGoogle': AppStrings.signUpWithGoogleAr,
          'alreadyHaveAccount': AppStrings.alreadyHaveAccountAr,
          'signIn': AppStrings.signInAr,
          'signUpWelcomeSentence': AppStrings.signUpWelcomeSentenceAr,
          'facebookSentence': AppStrings.facebookSentenceAr,
          'googleSentence': AppStrings.googleSentenceAr,
          'Doctor meeting': AppStrings.doctorDiagnosisAr,
          'Medical History': AppStrings.medicalHistoryAr,
          'Body Vitals': AppStrings.bodyVitalsAr,
          'Medical Images': AppStrings.medicalImagesAr,
          'hi': AppStrings.hiAr,
          'Home': AppStrings.homeAr,
          'Prescriptions': AppStrings.prescriptionsAr,
          'Analytics': AppStrings.analyticsAr,
          'Profile': AppStrings.profileAr,
          'Good Morning': AppStrings.goodMorningAr,
          'Good Evening': AppStrings.goodEveningAr,
          'Date ': AppStrings.dateAr,
          'Doctor Name ': AppStrings.doctorNameAr,
          'complain ': AppStrings.complainAr,
          'Doctor Diagnosis ': AppStrings.diagnosisAr,
          'pulse': AppStrings.pulseAr,
          'pressure': AppStrings.pressureAr,
          'sys': AppStrings.sysAr,
          'dia': AppStrings.diaAr,
          'mmhg':AppStrings.pressureUnitAr,
          'weight':AppStrings.weightAr,
          'kg':AppStrings.weightUnitAr,
          'Measurement date':AppStrings.measurementDateAr,
          'Add the new measurements':AppStrings.addMeasurementAr,
          'welcome input':AppStrings.welcomeInputDiaAr,
        },
      };
}
